Upgraded to neo4j 2.1.5 / Build succeeds
1. Also upped sesame to 2.7.13 (fixes RDFJSON error as described in issue #11)/

2. Further included commons-io dependency to fix this error when running tests
(when test succeed, commons-io seems to get picked up after, so not sure
whether this should not be fixed differently):

    executeInsert(org.neo4j.server.plugin.sparql.SPARQLPluginTest)  Time elapsed: 20.945 sec  <<< ERROR!
    java.lang.NoClassDefFoundError: org/apache/commons/io/input/BOMInputStream

3. Finally (and that's just locally, nothing changed in code for that), I had some strange error:

    The POM for org.eclipse.jetty:jetty-server:jar:9.0.5.v20130815 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

That was due to a corrupt local repository: I removed `~/.m2/org/eclipse/jetty and did a rebuild.